### ISSUE TITLE
Deployed somewhere ?

### ISSUE THREAD

**Issue by teolemon** [omnitrogen/foodscan#1]
Hello,
Pierre from Open Food Facts, I was curious as whether you had deployed your app somewhere, and where you found the Monsanto list :-)

**Comment by teolemon** [comment]
(Also, feel free to join us on the OFF Slack)

**Comment by felixwanders** [comment]
Hello @teolemon !

I didn't deploy my app, I made it just for "fun".

I found many lists of brands owned by Monsanto or using Monsanto product (https://feast.media/food-brands-owned-by-monsanto, https://www.bioalaune.com/fr/actualite-bio/10502/monsanto-produits-boycotter,...). They are all based on a [relatively old Greenpeace reports about GMO](https://secured-static.greenpeace.org/canada/Global/canada/report/2009/9/guideogm.pdf) and Monsanto Products. They might not be very relevant as of today... (but it was just to have a "base" for my app).

Greenpeace published a [more recent report](https://cdn.greenpeace.fr/site/uploads/2017/03/guide-OGM.pdf?_ga=2.10550260.1191141018.1535621703-801034202.1535621703), but it would require much more work to extract the data (maybe one day). There is also a [frequently update website about bee killer pesticides and GMO](https://greenpeace.fr/guetteur/marques/).

But still, all these infos are given by Greenpeace, so it might not be considered as a "relevant source"...

Thanks, I joined the OFF Slack 👍  Very interesting project!
